theme: jekyll-theme-slate
pages:
  - Concept:
    - Concept Generation: concept_generation.md
    - Concept Selection: concept_selection.md
    - Product Design Specification (PDS): PDS.md

toc:
  - title: Concept
    subfolderitems:
      - page: Concept Generation
        url: concept_generation.md
      - page: Concept Selection
        url: concept_selection.md
      - page: Product Design Specification (PDS)
        url: PDS.md
